name: 'Validate terrafrm'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init -backend=false
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Plan
      run: terraform validate
